config/routes.rb
RailsVideos::Application.routes.draw do

resources :auth_users
match "demo/hello" => "demo#hello"
match "demo/index" => "demo#index"
match "demo/other_hello" => "demo#other_hello"
resources :demo
resources :users
resources :projects
resources :sessions
resources :secret

end

app/models/auth_user.rb
class AuthUser < ActiveRecord::Base
  attr_accessible :email, :password_digest

  #validates_presence_of :password, :on => :create
  #has_secure_passsword

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :project_name

  def self.search(search)
    if search
    find(:all,:conditions => ['project_name LIKE ?',"%#{search}%"])
    else
    find(:all)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :password, :full_name

  def full_name
  [first_name,last_name].join(' ')

  end

  def full_name=(name)
  split=name.split(' ',2)
  self.first_name=split.first
  self.last_name=split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private

  def current_user
    @current_user ||= AuthUser.find(session[:auth_user_id]) if session[:auth_user_id]
  end

  helper_method :current_user
end

app/controllers/auth_users_controller.rb
class AuthUsersController < ApplicationController
  def new
    @auth_user=AuthUser.new
  end

  def create
    @auth_user=AuthUser.new(params[:auth_users])
    if @auth_user.save
      redirect_to projects_path, :notice => "Signed In"
    else
      render 'new'
    end

  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController


  def index
   # render 'hello'
    #render :action => :hello
  #redirect_to :action => :other_hello
  end

  def hello
  #  @array=[1,2,3,4,5]
    @id=params[:id].to_i
    @page=params[:page].to_i
   # render :text => "Hello Everyone!"
    #redirect_to("http://www.lynda.com")
  end

  def other_hello

  end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def create
    @project=Project.new(params[:project])
    @project.save
    redirect_to projects_path
  end

  def show
    @project=Project.find(params[:id])
  end

  def index
    @projects=Project.search(params[:search])
  end


  def edit
    @project=Project.find(params[:id])
  end

  def update
    @project=Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:success] = "Project updated."
      redirect_to @project
    end

  end
end

app/controllers/secret_controller.rb
class SecretController < ApplicationController
  http_basic_authenticate_with :name => "nayana", :password => "gharte"
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    auth_user=AuthUser.find_by_email(params[:email])
    if auth_user && auth_user.authenticate(params[:password])
      session[:auth_user_id]=auth_user.id
      redirect_to projects_path, :notice => "Logged in!"
    else
      flash.now.alert= "Invalid email or password"
      render 'new'
    end
  end

  def destroy
    session[:auth_user_id]=nil
    redirect_to demo_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #def new
   # @user=User.new
  #end

  def create
    @user=User.new(params[:user])
    @user.save
    redirect_to users_path
  end

  def index
   @users=User.all
  end

  def show
  @user=User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_users_helper.rb
module AuthUsersHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/secret_helper.rb
module SecretHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auth_users/new.html.erb
<h1>Sign Up</h1>

<%= form_for :auth_users do |f| %>
    <div class= "field">
      <%= f.label :email  %> <br>
      <%= f.text_field :email %> <br>
    </div>
    <div class= "field">
      <%= f.label :password  %> <br>
      <%= f.password_field :password  %><br>
    </div>
    <div class= "field">
      <%= f.label :password_confirmation  %> <br>
      <%= f.password_field :password_confirmation  %><br>
    </div>
    <div class= "action">
      <%= f.submit %>
    </div>
<% end %>

app/views/demo/hello.html.erb
<h1>Demo#Hello</h1> <br>

ID: <%= @id %> <br>

Next Page: <%= @page +1 %> <br>

<%= 1+1 %> <br>

<% target="world" %>

<%= "Hello #{target}" %> <br>

<% 3.times do %>
aaa:<%= 'xxx' %> <br>
<% end %>

<%= link_to("My first link",{:action => 'index' }) %>  <br>

<hr/>
 <%= params.inspect %>

app/views/demo/index.html.erb
<h1>Demo#Index</h1>
<p>Hello this is from Index page</p>

<%= link_to("Go back to hello",{:action => 'hello', :id => 20, :page => 5}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsVideos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<h1>Project</h1>
<%= form_for :project, :url => projects_path  do |f| %>

    <p>
      Project Name: <br>
      <%= f.text_field :project_name  %>
    </p>
    <p>
      <%= submit_tag 'Update' %>
    </p>
<% end %>

app/views/projects/index.html.erb
<%= form_tag projects_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
</p>
<% end %>

<% @projects.each do |project| %>
    <%= link_to project.project_name,project_path(project) %>
    <%= link_to "Edit", edit_project_path(project) %> <br><br>
<% end %>
<br><br>
<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>Project</h1>
<%= form_for :project, :url => projects_path  do |f| %>

    <p>
      Project Name: <br>
      <%= f.text_field :project_name  %>
    </p>
    <p>
      <%= submit_tag 'Submit' %>
    </p>
<% end %>

app/views/projects/show.html.erb
<h1>Project Details</h1>
<%= @project.project_name%>

app/views/secret/index.html.erb
<h1>Hello</h1>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= user.full_name%><br>
<% end %>

app/views/users/new.html.erb
<h1>Register</h1>
<%= form_for :user, :url => users_path  do |f| %>
    <p>
      Full Name <br>
      <%= f.text_field :full_name %>
    </p>
    <p>
      Password <br>
      <%= f.password_field :password  %>
    </p>
    <p>
      <%= submit_tag 'Register' %>
    </p>
<% end %>

app/views/users/show.html.erb
<%= @user.full_name%>